; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26732.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?qt_meta_stringdata_Squarus@@3Uqt_meta_stringdata_Squarus_t@@B DD 0ffffffffH ; qt_meta_stringdata_Squarus
	DD	07H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	053H
	DB	071H
	DB	075H
	DB	061H
	DB	072H
	DB	075H
	DB	073H
	DB	00H
?qt_meta_data_Squarus@@3QBIB DD 08H			; qt_meta_data_Squarus
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	ORG $+4
$SG142512 DB	'c:\qt\5.12.2\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG142513 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG142514 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG145247 DB	'c:\qt\5.12.2\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG145248 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG145249 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG145583 DB	'c:\qt\5.12.2\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG145584 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG145585 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG145919 DB	'c:\qt\5.12.2\msvc2017_64\include\qtcore\qmetatype.h', 00H
	ORG $+12
$SG145920 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG145921 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@Squarus@@UEBAPEBUQMetaObject@@XZ	; Squarus::metaObject
PUBLIC	?qt_metacast@Squarus@@UEAAPEAXPEBD@Z		; Squarus::qt_metacast
PUBLIC	?qt_metacall@Squarus@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; Squarus::qt_metacall
PUBLIC	?qt_static_metacall@Squarus@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Squarus::qt_static_metacall
PUBLIC	?staticMetaObject@Squarus@@2UQMetaObject@@B	; Squarus::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@Squarus@@2UQMetaObject@@B DB 030H DUP (?) ; Squarus::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@Squarus@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@Squarus@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@Squarus@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@Squarus@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@Squarus@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?qt_metacall@Squarus@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@Squarus@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@Squarus@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@Squarus@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@Squarus@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@Squarus@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@Squarus@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@Squarus@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@Squarus@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'Squarus::staticMetaObject'', COMDAT
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 66
	mov	rax, QWORD PTR __imp_?staticMetaObject@QMainWindow@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@Squarus@@2UQMetaObject@@B, rax
; Line 67
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_Squarus@@3Uqt_meta_stringdata_Squarus_t@@B
	mov	QWORD PTR ?staticMetaObject@Squarus@@2UQMetaObject@@B+8, rax
; Line 68
	lea	rax, OFFSET FLAT:?qt_meta_data_Squarus@@3QBIB
	mov	QWORD PTR ?staticMetaObject@Squarus@@2UQMetaObject@@B+16, rax
; Line 69
	lea	rax, OFFSET FLAT:?qt_static_metacall@Squarus@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; Squarus::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@Squarus@@2UQMetaObject@@B+24, rax
; Line 70
	mov	QWORD PTR ?staticMetaObject@Squarus@@2UQMetaObject@@B+32, 0
; Line 71
	mov	QWORD PTR ?staticMetaObject@Squarus@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@Squarus@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'Squarus::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@Squarus@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; Squarus::qt_static_metacall
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 58
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 63
	ret	0
?qt_static_metacall@Squarus@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Squarus::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@Squarus@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; Squarus::qt_metacall
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 89
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 90
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QMainWindow@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 91
	mov	eax, DWORD PTR _id$[rsp]
; Line 92
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@Squarus@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; Squarus::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@Squarus@@UEAAPEAXPEBD@Z PROC		; Squarus::qt_metacast
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 81
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 82
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 83
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_Squarus@@3Uqt_meta_stringdata_Squarus_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 84
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 85
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QMainWindow@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 86
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@Squarus@@UEAAPEAXPEBD@Z ENDP		; Squarus::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@Squarus@@UEBAPEBUQMetaObject@@XZ PROC	; Squarus::metaObject
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 76
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 77
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@Squarus@@2UQMetaObject@@B ; Squarus::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 78
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@Squarus@@UEBAPEBUQMetaObject@@XZ ENDP	; Squarus::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\5.12.2\msvc2017_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 95
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File c:\users\mattl\source\repos\squarus\squarus\generatedfiles\debug\moc_squarus.cpp
; Line 95
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
